export const USER_PROFILE = 'USER_PROFILE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const UPDATE_PHOTO = 'UPDATE_PHOTO';
export const SAVE_INFO_ON_LOGIN_USER = 'SAVE_INFO_ON_LOGIN_USER';




